common: &common
  adapter: postgresql
  encoding: utf8
  pool: 25
  username: vinhpham
  host: localhost
  password: qazokm
development:
  database: enapparte
  min_messages: warning
  <<: *common
staging:
  database: enapparte
  min_messages: warning
  <<: *common
test:
  database: enapparte
  min_messages: warning
  <<: *common